config:
  local:
    docker:
      cmd_bash_macos: /bin/bash
      cmd_dockermachine_macos: /usr/local/bin/docker-machine

      cmd_bash_windows: C:/Program Files/Git/bin/bash
      cmd_dockermachine_windows: C:/Program Files/Docker Toolbox/docker-machine.exe

    node:
      version: 5.1.0

    python:
      version: 3.5
      pip_version: 8.1.1
      # Invoke is currently pinned by this bug:
      #   https://github.com/pyinvoke/invoke/issues/345
      invoke_version: 0.12.2

    ruby:
      version: 2.2.3
      bundler_version: 1.10.6

  docker:
    travis:
      version: 1.11.2-0~trusty
      compose_version: 1.8.0-rc1
      compose_up_delay: 60

compile_config:
  entries:
    - in:  requirements3.in.in
      out: requirements3.in
    - in:  .travis.yml.in
      out: .travis.yml

compile_docker_localize:
  entries:
    - in:  tests/test-compose.yml
      out: tests/test-compose.localized.yml
    - in:  _config-test.yml
      out: _config-test.localized.yml
